### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by 18398639574** [YCG09/chinese_ocr#102]
Epoch 1/10
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/shuzhilian/anaconda3/envs/wenbenzu/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/shuzhilian/anaconda3/envs/wenbenzu/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/shuzhilian/anaconda3/envs/wenbenzu/lib/python3.6/site-packages/keras/utils/data_utils.py", line 630, in data_generator_task
    generator_output = next(self._generator)
  File "train.py", line 93, in gen
    img1 = Image.open(os.path.join(image_path, j)).convert('L')
  File "/home/shuzhilian/anaconda3/envs/wenbenzu/lib/python3.6/site-packages/PIL/Image.py", line 2477, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './images/22529765_1190300395.jpg'

Traceback (most recent call last):
  File "train.py", line 169, in <module>
    callbacks = [checkpoint, earlystop, changelr, tensorboard])
  File "/home/shuzhilian/anaconda3/envs/wenbenzu/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/shuzhilian/anaconda3/envs/wenbenzu/lib/python3.6/site-packages/keras/engine/training.py", line 2065, in fit_generator
    generator_output = next(output_generator)
StopIteration

**Comment by fire717** [comment]
你是自己的数据集吧，看下对应生成的txt有没有问题，这个报错是找不到训练图片

**Comment by sxk000** [comment]
你的问题解决了嘛？我也是报这个错？到底是什么原因呀？

**Comment by xiaotongtong9293** [comment]
我也有这个问题，迫切想知道，有人有解决了么？

**Comment by xiaotongtong9293** [comment]
同样报错，请问有人解决了么？
