### ISSUE TITLE
请问运行train.py需要的软件版本

### ISSUE THREAD

**Issue by cyangsn** [YCG09/chinese_ocr#13]
我的本机软件版本为python2.7，keras2.14，tensorflow-gpu1.3.0，可以正常运行demo程序。但在进行模型训练时，出现以下错误：
-----------Start training-----------
Epoch 1/10
Traceback (most recent call last):
  File "train.py", line 173, in <module>
    callbacks = [checkpoint, earlystop, changelr, tensorboard])
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2212, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 779, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 644, in _data_generator_task
    generator_output = next(self._generator)
  File "train.py", line 108, in gen
    labels[i, :len(str)] =[int(i) - 1 for i in str]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.

我将keras升级到最新版本2.16和旧版本keras2.08，均显示keras部分出现异常。采用python3.4运行train.py，也不能正常运行。

请问各位，大家都能正常运行train.py吗？我的软件配置的版本存在什么问题吗？
非常感谢！

**Comment by YCG09** [comment]
程序是在py3.5环境开发的，2.7上的训练部分没有测试过，我抽空看看

**Comment by wyj2046** [comment]
用2.7出现了一样的问题
