### ISSUE TITLE
多GPU训练

### ISSUE THREAD

**Issue by WHQCHINA** [YCG09/chinese_ocr#172]
@YCG09 多GPU训练报错：
-----------Start training-----------
Traceback (most recent call last):
  File "train.py", line 189, in <module>
    callbacks = [checkpoint, changelr, tensorboard])
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training_generator.py", line 93, in fit_generator
    callbacks.set_model(callback_model)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 52, in set_model
    callback.set_model(model)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 746, in set_model
    self.sess = K.get_session()
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 197, in get_session
    [tf.is_variable_initialized(v) for v in candidate_vars])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'replica_0/lambda_3/Slice': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
不知道啥原因

**Comment by YCG09** [comment]
查查历史问题，有关于多GPU的

**Comment by WHQCHINA** [comment]
@YCG09 已经解决

**Comment by zhouyuangan** [comment]
@WHQCHINA 能提供一下你的方案吗

**Comment by WHQCHINA** [comment]
@WHQCHINA 
1. 在train.py文件model.compile(loss={'ctc': lambda y_true, y_pred: y_pred}, optimizer='adam', metrics=['accuracy'])前添加model = multi_gpu_model(model, gpus=2)
2. 之后用下面代码生成最终模型：
word_952.jpg
#-- coding:utf-8 --
from keras import backend as K
import os
import shutil
import tensorflow as tf
import keys
import densenet
from keras.layers import Input
from keras.models import Model
from keras.utils import multi_gpu_model
reload(densenet)
characters = keys.alphabet[:]
characters = characters[1:] + u'卍'
nclass = len(characters)
print nclass
input = Input(shape=(32, None, 1), name='the_input')
y_pred= densenet.dense_cnn(input, nclass)
single_basemodel = Model(inputs=input, outputs=y_pred)
modelPath = os.path.join('models/weights_densenet-08-9.06.h5')
basemodel = multi_gpu_model(single_basemodel, gpus=2)
basemodel.load_weights(modelPath)
single_basemodel.save('weights_densenet-08-9.06.h5') 
print('done...')

**Comment by xinyuegtxy** [comment]
> @zhouyuangan
> 
> 1. 在train.py文件model.compile(loss={'ctc': lambda y_true, y_pred: y_pred}, optimizer='adam', metrics=['accuracy'])前添加model = multi_gpu_model(model, gpus=2)
> 2. 之后用下面代码生成最终模型：
>    word_952.jpg
>    #-- coding:utf-8 --
>    from keras import backend as K
>    import os
>    import shutil
>    import tensorflow as tf
>    import keys
>    import densenet
>    from keras.layers import Input
>    from keras.models import Model
>    from keras.utils import multi_gpu_model
>    reload(densenet)
>    characters = keys.alphabet[:]
>    characters = characters[1:] + u'卍'
>    nclass = len(characters)
>    print nclass
>    input = Input(shape=(32, None, 1), name='the_input')
>    y_pred= densenet.dense_cnn(input, nclass)
>    single_basemodel = Model(inputs=input, outputs=y_pred)
>    modelPath = os.path.join('models/weights_densenet-08-9.06.h5')
>    basemodel = multi_gpu_model(single_basemodel, gpus=2)
>    basemodel.load_weights(modelPath)
>    single_basemodel.save('weights_densenet-08-9.06.h5')
>    print('done...')

你这个有问题，keras的多gpu，multi model加载不行，直接tf多卡训练，调大batch size，这样就行了，不知道对不对

**Comment by xinyuegtxy** [comment]
multi_gpu_model===>出现下面的错误
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'replica_0/lambda_3/Slice': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.

**Comment by WHQCHINA** [comment]
@xinyuegtxy 如果你代码中使用了设置gpu和使用GPU显存比率，你需要把它注销掉，应该就好了

**Comment by xiechunhong** [comment]
@xinyuegtxy 我遇到同样的问题，通过改 get_session() 方法解决，主要是加上 allow_soft_placement=True
`
def get_session():
    return tf.Session(config=tf.ConfigProto(allow_soft_placement=True))
`
