### ISSUE TITLE
测试的时候通过，训练的时候报了这个问题，也下载了最新的train.py，依然不行。python3.6

### ISSUE THREAD

**Issue by wjnodejs** [YCG09/chinese_ocr#185]
-----------Start training-----------
Epoch 1/10
Traceback (most recent call last):
File "train.py", line 169, in 
callbacks = [checkpoint, earlystop, changelr, tensorboard])
File "/opt/software/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
return func(*args, **kwargs)
File "/opt/software/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
initial_epoch=initial_epoch)
File "/opt/software/anaconda3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 177, in fit_generator
generator_output = next(output_generator)
File "/opt/software/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 793, in get
six.reraise(value.class, value, value.traceback)
File "/opt/software/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
raise value
File "/opt/software/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
generator_output = next(self._generator)
File "train.py", line 96, in gen
x[i] = np.expand_dims(img,axis=2)
ValueError: could not broadcast input array from shape (32,256,1) into shape (32,280,1)
swig/python detected a memory leak of type 'int64_t *', no destructor foun

**Comment by xiaoyubing** [comment]
输入的图片大小不对，你再gen函数中增加一个resize动作吧，免得数据大小不一致跑不起来

发送自 Windows 10 版邮件应用

发件人: wjnodejs
发送时间: 2019年3月14日 16:37
收件人: YCG09/chinese_ocr
抄送: Subscribed
主题: [YCG09/chinese_ocr]=?UTF-8?Q?_=E6=B5=8B=E8=AF=95=E7=9A=84=E6=97=B6=E5=80=99=E9=80=9A=E8=BF=87=EF=BC=8C=E8=AE=AD=E7=BB=83=E7=9A=84=E6=97=B6=E5=80=99=E6=8A=A5=E4=BA=86=E8=BF=99=E4=B8=AA=E9=97=AE=E9=A2=98=EF=BC=8C=E4=B9=9F=E4=B8=8B=E8=BD=BD=E4=BA=86=E6=9C=80=E6=96=B0=E7=9A=84train.py=EF=BC=8C=E4=BE=9D=E7=84=B6=E4=B8=8D=E8=A1=8C=E3=80=82python3.6?==?UTF-8?Q?_=28#185=29?=

-----------Start training-----------
Epoch 1/10
Traceback (most recent call last):
File "train.py", line 169, in
callbacks = [checkpoint, earlystop, changelr, tensorboard])
File "/opt/software/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
return func(*args, **kwargs)
File "/opt/software/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
initial_epoch=initial_epoch)
File "/opt/software/anaconda3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 177, in fit_generator
generator_output = next(output_generator)
File "/opt/software/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 793, in get
six.reraise(value.class, value, value.traceback)
File "/opt/software/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
raise value
File "/opt/software/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
generator_output = next(self._generator)
File "train.py", line 96, in gen
x[i] = np.expand_dims(img,axis=2)
ValueError: could not broadcast input array from shape (32,256,1) into shape (32,280,1)
swig/python detected a memory leak of type 'int64_t *', no destructor foun

**Comment by 666888985** [comment]
@xiaoyubing ,你好，测试代码有吗？我看项目里面给的demo.py只有ctpn检测部分，没有densenet+ctc的识别部分的测试代码
