### ISSUE TITLE
运行demo.py不出结果？

### ISSUE THREAD

**Issue by squallzhong** [YCG09/chinese_ocr#21]
楼主
  运行demo.py，结果如下：
root@145f47f2e811:/data/chinese_ocr# python demo.py
2018-05-11 06:01:19.437201: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-11 06:01:19.437315: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-11 06:01:19.437474: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-05-11 06:01:19.437667: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-11 06:01:19.437881: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_cls_score/Reshape_1:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)
Tensor("Reshape_2:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_bbox_pred/Reshape_1:0", shape=(?, ?, ?, 40), dtype=float32)
Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
Loading network VGGnet_test...
Restoring from ./ctpn/checkpoints/VGGnet_fast_rcnn_iter_50000.ckpt...
done
Using TensorFlow backend.
Killed

在相应目录没产生结果，请教怎么回事？

**Comment by kajdkfksncnd** [comment]
我能问一下吗？上述问题您是怎么解决的呢，我也遇到了同样的问题

**Comment by squallzhong** [comment]
我没用楼主提供的ctpn,我使用https://github.com/eragonruan/text-detection-ctpn这个重新编译了一下，再替换楼主的ctpn目录,就OK了

**Comment by zymize** [comment]
@squallzhong 我也替换了但是出现错误
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    import ocr
  File "/data/nextcloud/dbc2017/files/jupyter/chinese_ocr/ocr.py", line 12, in <module>
    from ctpn.text_detect import text_detect
ModuleNotFoundError: No module named 'ctpn'

这个请问怎么解决呢？
