### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './images/47442484_1199315388.jpg'

### ISSUE THREAD

**Issue by sxk000** [YCG09/chinese_ocr#233]
FileNotFoundError: [Errno 2] No such file or directory: './images/47442484_1199315388.jpg'

在：数据集：https://pan.baidu.com/s/1QkI7kjah8SPHwOQ40rS1Pw (密码：lu7m)下载了 data_train.txt和data_test.txt，放到了train文件夹下，下载了Chinese_dataset.rar解压后，把得到的images和labels.txt放到了train文件夹下
然后运行python train.py文件，报如下错误：

-----------Start training-----------
Epoch 1/10
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 630, in data_generator_task
    generator_output = next(self._generator)
  File "train.py", line 93, in gen
    img1 = Image.open(os.path.join(image_path, j)).convert('L')
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2258, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './images/47442484_1199315388.jpg'

Traceback (most recent call last):
  File "train.py", line 169, in <module>
    callbacks = [checkpoint, earlystop, changelr, tensorboard])
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2083, in fit_generator
    generator_output = next(output_generator)
StopIteration

这是什么原因导致的呢？需要修改代码吗？还是我的操作有问题呢？我应该怎么办呢？

**Comment by sxk000** [comment]
图片数据应该用  数据集：https://pan.baidu.com/s/1QkI7kjah8SPHwOQ40rS1Pw (密码：lu7m)下载的  synthetic_chinese_string_dataset.rar中的images中的图片，而不是Chinese_dataset.rar中的images中的图片
此问题已经完美解决！

**Comment by kennybai** [comment]
> 图片数据应该用 数据集：https://pan.baidu.com/s/1QkI7kjah8SPHwOQ40rS1Pw (密码：lu7m)下载的 synthetic_chinese_string_dataset.rar中的images中的图片，而不是Chinese_dataset.rar中的images中的图片
> 此问题已经完美解决！
请问下 split_label.py 下的 path和gt_path分别指什么路径

**Comment by sxk000** [comment]
> > 图片数据应该用 数据集：https://pan.baidu.com/s/1QkI7kjah8SPHwOQ40rS1Pw (密码：lu7m)下载的 synthetic_chinese_string_dataset.rar中的images中的图片，而不是Chinese_dataset.rar中的images中的图片
> > 此问题已经完美解决！
> > 请问下 split_label.py 下的 path和gt_path分别指什么路径

**Comment by sxk000** [comment]
> > 图片数据应该用 数据集：https://pan.baidu.com/s/1QkI7kjah8SPHwOQ40rS1Pw (密码：lu7m)下载的 synthetic_chinese_string_dataset.rar中的images中的图片，而不是Chinese_dataset.rar中的images中的图片
> > 此问题已经完美解决！
> > 请问下 split_label.py 下的 path和gt_path分别指什么路径

path = 'VOC2007/JPEGImages'
gt_path = 'VOC2007/Annotations'
out_path = 're_image'
@ @kennybai

**Comment by kennybai** [comment]
> > > 图片数据应该用 数据集：https://pan.baidu.com/s/1QkI7kjah8SPHwOQ40rS1Pw (密码：lu7m)下载的 synthetic_chinese_string_dataset.rar中的images中的图片，而不是Chinese_dataset.rar中的images中的图片
> > > 此问题已经完美解决！
> > > 请问下 split_label.py 下的 path和gt_path分别指什么路径
> 
> path = 'VOC2007/JPEGImages'
> gt_path = 'VOC2007/Annotations'
> out_path = 're_image'
> @ @kennybai
感谢大哥这么快回复，还有一个问题请教下，在split_labell.py中会利用gt_path生成gt_file文件路径，如下 gt_file = os.path.join(gt_path, 'gt_' + stem + '.txt'),但是按照老哥刚刚说，gt_path='VOC2007/Annotations'，并没有发现gt_xxxx.txt文件。请问这些文件在哪里，请教了

**Comment by kennybai** [comment]
> > > 图片数据应该用 数据集：https://pan.baidu.com/s/1QkI7kjah8SPHwOQ40rS1Pw (密码：lu7m)下载的 synthetic_chinese_string_dataset.rar中的images中的图片，而不是Chinese_dataset.rar中的images中的图片
> > > 此问题已经完美解决！
> > > 请问下 split_label.py 下的 path和gt_path分别指什么路径
> 
> path = 'VOC2007/JPEGImages'
> gt_path = 'VOC2007/Annotations'
> out_path = 're_image'
> @ @kennybai
我的qq: 1525779272，大哥，有些问题请教你，麻烦加下。

**Comment by sxk000** [comment]
@kennybai 时间久了我也不清楚了，我最近也没有弄这个相关的东西，可能我回答的那两个路径也不对，你在好好看看代码，或者请教一下别人吧，非常抱歉！
