### ISSUE TITLE
环境部署问题

### ISSUE THREAD

**Issue by darknessp** [YCG09/chinese_ocr#28]
windows下用cygwin运行setup.sh报出如下错误，请问该怎么解决呢？

Traceback (most recent call last):
  File "setup_cpu.py", line 57, in <module>
    cmdclass={'build_ext': custom_build_ext},
  File "D:\Program Files\Python\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Program Files\Python\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Program Files\Python\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Program Files\Python\lib\site-packages\Cython\Distutils\build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "D:\Program Files\Python\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "setup_cpu.py", line 37, in build_extensions
    customize_compiler_for_nvcc(self.compiler)
  File "setup_cpu.py", line 23, in customize_compiler_for_nvcc
    default_compiler_so = self.compiler_so
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'
mv: 无法获取'utils/*' 的文件状态(stat): No such file or directory

**Comment by YCG09** [comment]
我没在windows下测试过，根据[asd](https://github.com/eragonruan/text-detection-ctpn/issues/112)来看好像不行

**Comment by darknessp** [comment]
@YCG09 
这个怎么解决呢
mv: 无法获取'utils/*' 的文件状态(stat): No such file or directory

**Comment by YCG09** [comment]
是因为前面没有执行成功，没有生成utils文件夹，所以mv失败了

**Comment by piaobuliao** [comment]
可以参考  https://github.com/eragonruan/text-detection-ctpn/issues/73
在windows下cpu模式是可以的 我刚弄好

**Comment by flag2freefish** [comment]
请问，这第一个问题怎么解决的呢？

**Comment by flag2freefish** [comment]
我按楼上的吧setup_cpu.py改成楼上的那个文件，运行demo没问题，暂时不知道训练行不行
环境：win7+cpu+vs2017，极其低配版
