### ISSUE TITLE
ImportError: No module named Cython.Build

### ISSUE THREAD

**Issue by banbsyip** [YCG09/chinese_ocr#291]
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
mv: cannot stat 'utils/*': No such file or directory

**Comment by banbsyip** [comment]
运行sh setup.sh出错

**Comment by banbsyip** [comment]
换成虚拟机跑，又是另外的问题：
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 26, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDA_HOME
mv: 无法获取'utils/*' 的文件状态(stat): 没有那个文件或目录

**Comment by BI4O** [comment]
自己手动一行一行写进去就好
