### ISSUE TITLE
运行demo.py时出现问题

### ISSUE THREAD

**Issue by ghost** [YCG09/chinese_ocr#318]
**root@DESKTOP-J2JK9EH:/mnt/c/Ubuntu/chinese_ocr-master# python demo.py
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    import ocr
  File "/mnt/c/Ubuntu/chinese_ocr-master/ocr.py", line 4, in <module>
    import cv2
  File "/usr/local/lib/python2.7/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory**

**Comment by zymize** [comment]
你好 这个怎么解决  我也出现了ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory
