### ISSUE TITLE
请教 Keras模型如何转换成TensorFlow的模型？

### ISSUE THREAD

**Issue by xiaomochen520** [YCG09/chinese_ocr#52]
大佬，请教个问题，Keras模型如何转换成TensorFlow的模型？
我想把这个模型移植到Android平台上去，我在网上找的相关的信息很少，
而且 训练完成之后的模型 使用  load_model() 方法 会报错，能帮忙看一下是什么问题么？

```python
Traceback (most recent call last):
  File "convert.py", line 51, in <module>
    net_model = load_model(weight_file_path)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 290, in load_model
    sample_weight_mode=sample_weight_mode)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 127, in compile
    loss_functions.append(losses.get(loss.get(name)))
  File "/usr/local/lib/python3.5/dist-packages/keras/losses.py", line 122, in get
    return deserialize(identifier)
  File "/usr/local/lib/python3.5/dist-packages/keras/losses.py", line 114, in deserialize
    printable_module_name='loss function')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 165, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown loss function:<lambda>

```

convert 文件源码

```python
# coding=utf-8
import sys

from keras.models import load_model
import tensorflow as tf
import os
import os.path as osp
from keras import backend as K


def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
    """
    Freezes the state of a session into a prunned computation graph.

    Creates a new computation graph where variable nodes are replaced by
    constants taking their current value in the session. The new graph will be
    prunned so subgraphs that are not neccesary to compute the requested
    outputs are removed.
    @param session The TensorFlow session to be frozen.
    @param keep_var_names A list of variable names that should not be frozen,
                          or None to freeze all the variables in the graph.
    @param output_names Names of the relevant graph outputs.
    @param clear_devices Remove the device directives from the graph for better portability.
    @return The frozen graph definition.
    """
    from tensorflow.python.framework.graph_util import convert_variables_to_constants
    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.global_variables()]
        input_graph_def = graph.as_graph_def()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
        frozen_graph = convert_variables_to_constants(session, input_graph_def,
                                                      output_names, freeze_var_names)
        return frozen_graph


input_fld = sys.path[0]
weight_file = 'model.h5'
output_graph_name = 'tensor_model.pb'

output_fld = input_fld + '/tensorflow_model/'
if not os.path.isdir(output_fld):
    os.mkdir(output_fld)
weight_file_path = osp.join(input_fld, weight_file)

K.set_learning_phase(0)
net_model = load_model(weight_file_path)


print('input is :', net_model.input.name)
print ('output is:', net_model.output.name)

sess = K.get_session()

frozen_graph = freeze_session(K.get_session(), output_names=[net_model.output.op.name])

from tensorflow.python.framework import graph_io

graph_io.write_graph(frozen_graph, output_fld, output_graph_name, as_text=False)

print('saved the constant graph (ready for inference) at: ', osp.join(output_fld, output_graph_name))

```

**Comment by dlml** [comment]
我试了一下 转过去 最后好多op也不支持

**Comment by xiaomochen520** [comment]
@dlml  咋整，我都卡在这里快两个月了

**Comment by dlml** [comment]
你用tensorflow写一个这样的，用keras转过去也有毛病，我测试了，mnist用tensorflow生产的模型可以转成tflite，正常加载。但是用keras生产的模型再转成tensorflow，量化的时候会有很多op不支持的bug

**Comment by dlml** [comment]
你可以参考这个keras转成tf模型，https://github.com/amir-abdi/keras_to_tensorflow

但是最后量化会有bug

**Comment by dlml** [comment]
@xiaomochen520  怎么样啊 能转过去了没

**Comment by xiaomochen520** [comment]
@dlml  谢谢你的方法，我试过了，成功转换了。但是我遇到了 跟你一样的BUG，提示缺少op 这个问题你解决了么？

**Comment by xiaomochen520** [comment]
@dlml  提示op不支持的BUG 你解决了么？

**Comment by dlml** [comment]
你可以用tensorflow封装的keras进行训练，就不会出现这样的bug

**Comment by strongman1995** [comment]
我是用的 tensorflow 封装的 keras ，在 densenet.py 把导入的包都替换掉
`from tensorflow import keras
Input = keras.layers.Input
Sequential = keras.models.Sequential
Conv2D = keras.layers.Conv2D
Dense = keras.layers.Dense
Activation = keras.layers.Activation
Flatten = keras.layers.Flatten
KerasModel = keras.models.Model
l2 = keras.regularizers.l2
AveragePooling2D = keras.layers.AveragePooling2D
Dropout = keras.layers.Dropout
BatchNormalization = keras.layers.BatchNormalization
GlobalAveragePooling2D = keras.layers.GlobalAveragePooling2D
Conv2DTranspose = keras.layers.Conv2DTranspose
ZeroPadding2D = keras.layers.ZeroPadding2D
Permute = keras.layers.Permute
Reshape = keras.layers.Reshape
concatenate = keras.layers.concatenate
TimeDistributed = keras.layers.TimeDistributed
Model = keras.models.Model`
用 dense_cnn构建一个 Model，
然后tf.keras的模型和 keras 模型一样，用load_weights也能正确加载权重

**Comment by yjfncu** [comment]
你们转换后的pb模型，输入图片宽度是280吗？我想要pb输入图片不定长，我看原始h5模型识别的时候输入的图片宽度就不是280
